//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agsResource"
})
@XmlRootElement(name = "ags:resources")
public class AgsResources {

    @XmlAttribute(name = "xmlns:ags")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsAgs;
    @XmlAttribute(name = "xmlns:dc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsDc;
    @XmlAttribute(name = "xmlns:agls")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsAgls;
    @XmlAttribute(name = "xmlns:dcterms")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsDcterms;
    @XmlElement(name = "ags:resource", required = true)
    protected List<AgsResource> agsResource;

    /**
     * Gets the value of the xmlnsAgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsAgs() {
        if (xmlnsAgs == null) {
            return "http://purl.org/agmes/1.1/";
        } else {
            return xmlnsAgs;
        }
    }

    /**
     * Sets the value of the xmlnsAgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsAgs(String value) {
        this.xmlnsAgs = value;
    }

    /**
     * Gets the value of the xmlnsDc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsDc() {
        if (xmlnsDc == null) {
            return "http://purl.org/dc/elements/1.1/";
        } else {
            return xmlnsDc;
        }
    }

    /**
     * Sets the value of the xmlnsDc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsDc(String value) {
        this.xmlnsDc = value;
    }

    /**
     * Gets the value of the xmlnsAgls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsAgls() {
        if (xmlnsAgls == null) {
            return "http://www.naa.gov.au/recordkeeping/gov_online/agls/1.2";
        } else {
            return xmlnsAgls;
        }
    }

    /**
     * Sets the value of the xmlnsAgls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsAgls(String value) {
        this.xmlnsAgls = value;
    }

    /**
     * Gets the value of the xmlnsDcterms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsDcterms() {
        if (xmlnsDcterms == null) {
            return "http://purl.org/dc/terms/";
        } else {
            return xmlnsDcterms;
        }
    }

    /**
     * Sets the value of the xmlnsDcterms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsDcterms(String value) {
        this.xmlnsDcterms = value;
    }

    /**
     * Gets the value of the agsResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agsResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgsResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgsResource }
     * 
     * 
     */
    public List<AgsResource> getAgsResource() {
        if (agsResource == null) {
            agsResource = new ArrayList<AgsResource>();
        }
        return this.agsResource;
    }

}
