//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dcTitle",
    "dcCreator",
    "dcPublisher",
    "dcDate",
    "dcSubject",
    "dcDescription",
    "dcIdentifier",
    "dcType",
    "dcFormat",
    "dcLanguage",
    "dcRelation",
    "aglsAvailability",
    "dcSource",
    "dcCoverage",
    "dcRights",
    "agsCitation"
})
@XmlRootElement(name = "ags:resource")
public class AgsResource {

    @XmlAttribute(name = "ags:ARN", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String agsARN;
    @XmlElement(name = "dc:title", required = true)
    protected List<DcTitle> dcTitle;
    @XmlElement(name = "dc:creator")
    protected List<DcCreator> dcCreator;
    @XmlElement(name = "dc:publisher")
    protected List<DcPublisher> dcPublisher;
    @XmlElement(name = "dc:date")
    protected List<DcDate> dcDate;
    @XmlElement(name = "dc:subject")
    protected List<DcSubject> dcSubject;
    @XmlElement(name = "dc:description")
    protected List<DcDescription> dcDescription;
    @XmlElement(name = "dc:identifier")
    protected List<DcIdentifier> dcIdentifier;
    @XmlElement(name = "dc:type")
    protected List<DcType> dcType;
    @XmlElement(name = "dc:format")
    protected List<DcFormat> dcFormat;
    @XmlElement(name = "dc:language")
    protected List<DcLanguage> dcLanguage;
    @XmlElement(name = "dc:relation")
    protected List<DcRelation> dcRelation;
    @XmlElement(name = "agls:availability")
    protected List<AglsAvailability> aglsAvailability;
    @XmlElement(name = "dc:source")
    protected List<DcSource> dcSource;
    @XmlElement(name = "dc:coverage")
    protected List<DcCoverage> dcCoverage;
    @XmlElement(name = "dc:rights")
    protected List<DcRights> dcRights;
    @XmlElement(name = "ags:citation")
    protected List<AgsCitation> agsCitation;

    /**
     * Gets the value of the agsARN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgsARN() {
        return agsARN;
    }

    /**
     * Sets the value of the agsARN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgsARN(String value) {
        this.agsARN = value;
    }

    /**
     * Gets the value of the dcTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcTitle }
     * 
     * 
     */
    public List<DcTitle> getDcTitle() {
        if (dcTitle == null) {
            dcTitle = new ArrayList<DcTitle>();
        }
        return this.dcTitle;
    }

    /**
     * Gets the value of the dcCreator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcCreator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcCreator }
     * 
     * 
     */
    public List<DcCreator> getDcCreator() {
        if (dcCreator == null) {
            dcCreator = new ArrayList<DcCreator>();
        }
        return this.dcCreator;
    }

    /**
     * Gets the value of the dcPublisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcPublisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcPublisher }
     * 
     * 
     */
    public List<DcPublisher> getDcPublisher() {
        if (dcPublisher == null) {
            dcPublisher = new ArrayList<DcPublisher>();
        }
        return this.dcPublisher;
    }

    /**
     * Gets the value of the dcDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcDate }
     * 
     * 
     */
    public List<DcDate> getDcDate() {
        if (dcDate == null) {
            dcDate = new ArrayList<DcDate>();
        }
        return this.dcDate;
    }

    /**
     * Gets the value of the dcSubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcSubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcSubject }
     * 
     * 
     */
    public List<DcSubject> getDcSubject() {
        if (dcSubject == null) {
            dcSubject = new ArrayList<DcSubject>();
        }
        return this.dcSubject;
    }

    /**
     * Gets the value of the dcDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcDescription }
     * 
     * 
     */
    public List<DcDescription> getDcDescription() {
        if (dcDescription == null) {
            dcDescription = new ArrayList<DcDescription>();
        }
        return this.dcDescription;
    }

    /**
     * Gets the value of the dcIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcIdentifier }
     * 
     * 
     */
    public List<DcIdentifier> getDcIdentifier() {
        if (dcIdentifier == null) {
            dcIdentifier = new ArrayList<DcIdentifier>();
        }
        return this.dcIdentifier;
    }

    /**
     * Gets the value of the dcType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcType }
     * 
     * 
     */
    public List<DcType> getDcType() {
        if (dcType == null) {
            dcType = new ArrayList<DcType>();
        }
        return this.dcType;
    }

    /**
     * Gets the value of the dcFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcFormat }
     * 
     * 
     */
    public List<DcFormat> getDcFormat() {
        if (dcFormat == null) {
            dcFormat = new ArrayList<DcFormat>();
        }
        return this.dcFormat;
    }

    /**
     * Gets the value of the dcLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcLanguage }
     * 
     * 
     */
    public List<DcLanguage> getDcLanguage() {
        if (dcLanguage == null) {
            dcLanguage = new ArrayList<DcLanguage>();
        }
        return this.dcLanguage;
    }

    /**
     * Gets the value of the dcRelation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcRelation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcRelation }
     * 
     * 
     */
    public List<DcRelation> getDcRelation() {
        if (dcRelation == null) {
            dcRelation = new ArrayList<DcRelation>();
        }
        return this.dcRelation;
    }

    /**
     * Gets the value of the aglsAvailability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aglsAvailability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAglsAvailability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AglsAvailability }
     * 
     * 
     */
    public List<AglsAvailability> getAglsAvailability() {
        if (aglsAvailability == null) {
            aglsAvailability = new ArrayList<AglsAvailability>();
        }
        return this.aglsAvailability;
    }

    /**
     * Gets the value of the dcSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcSource }
     * 
     * 
     */
    public List<DcSource> getDcSource() {
        if (dcSource == null) {
            dcSource = new ArrayList<DcSource>();
        }
        return this.dcSource;
    }

    /**
     * Gets the value of the dcCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcCoverage }
     * 
     * 
     */
    public List<DcCoverage> getDcCoverage() {
        if (dcCoverage == null) {
            dcCoverage = new ArrayList<DcCoverage>();
        }
        return this.dcCoverage;
    }

    /**
     * Gets the value of the dcRights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcRights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcRights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcRights }
     * 
     * 
     */
    public List<DcRights> getDcRights() {
        if (dcRights == null) {
            dcRights = new ArrayList<DcRights>();
        }
        return this.dcRights;
    }

    /**
     * Gets the value of the agsCitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agsCitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgsCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgsCitation }
     * 
     * 
     */
    public List<AgsCitation> getAgsCitation() {
        if (agsCitation == null) {
            agsCitation = new ArrayList<AgsCitation>();
        }
        return this.agsCitation;
    }

}
