//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dctermsDateIssued"
})
@XmlRootElement(name = "dc:date")
public class DcDate {

    @XmlElement(name = "dcterms:dateIssued", required = true)
    protected DctermsDateIssued dctermsDateIssued;

    /**
     * Gets the value of the dctermsDateIssued property.
     * 
     * @return
     *     possible object is
     *     {@link DctermsDateIssued }
     *     
     */
    public DctermsDateIssued getDctermsDateIssued() {
        return dctermsDateIssued;
    }

    /**
     * Sets the value of the dctermsDateIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link DctermsDateIssued }
     *     
     */
    public void setDctermsDateIssued(DctermsDateIssued value) {
        this.dctermsDateIssued = value;
    }

}
