//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf"
})
@XmlRootElement(name = "dc:relation")
public class DcRelation {

    @XmlElements({
        @XmlElement(name = "dcterms:isPartOf", type = DctermsIsPartOf.class),
        @XmlElement(name = "dcterms:hasPart", type = DctermsHasPart.class),
        @XmlElement(name = "dcterms:isVersionOf", type = DctermsIsVersionOf.class),
        @XmlElement(name = "dcterms:hasVersion", type = DctermsHasVersion.class),
        @XmlElement(name = "dcterms:isFormatOf", type = DctermsIsFormatOf.class),
        @XmlElement(name = "dcterms:hasFormat", type = DctermsHasFormat.class),
        @XmlElement(name = "dcterms:references", type = DctermsReferences.class),
        @XmlElement(name = "dcterms:isReferencedBy", type = DctermsIsReferencedBy.class),
        @XmlElement(name = "dcterms:isRequiredBy", type = DctermsIsRequiredBy.class),
        @XmlElement(name = "dcterms:requires", type = DctermsRequires.class),
        @XmlElement(name = "dcterms:isReplacedBy", type = DctermsIsReplacedBy.class),
        @XmlElement(name = "dcterms:replaces", type = DctermsReplaces.class),
        @XmlElement(name = "ags:relationHasTranslation", type = AgsRelationHasTranslation.class),
        @XmlElement(name = "ags:relationIsTranslationOf", type = AgsRelationIsTranslationOf.class)
    })
    protected List<Object> dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf;

    /**
     * Gets the value of the dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DctermsIsPartOf }
     * {@link DctermsHasPart }
     * {@link DctermsIsVersionOf }
     * {@link DctermsHasVersion }
     * {@link DctermsIsFormatOf }
     * {@link DctermsHasFormat }
     * {@link DctermsReferences }
     * {@link DctermsIsReferencedBy }
     * {@link DctermsIsRequiredBy }
     * {@link DctermsRequires }
     * {@link DctermsIsReplacedBy }
     * {@link DctermsReplaces }
     * {@link AgsRelationHasTranslation }
     * {@link AgsRelationIsTranslationOf }
     * 
     * 
     */
    public List<Object> getDctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf() {
        if (dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf == null) {
            dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf = new ArrayList<Object>();
        }
        return this.dctermsIsPartOfOrDctermsHasPartOrDctermsIsVersionOfOrDctermsHasVersionOrDctermsIsFormatOfOrDctermsHasFormatOrDctermsReferencesOrDctermsIsReferencedByOrDctermsIsRequiredByOrDctermsRequiresOrDctermsIsReplacedByOrDctermsReplacesOrAgsRelationHasTranslationOrAgsRelationIsTranslationOf;
    }

}
