//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.agroknow.process.Annotatable;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "agsSubjectThesaurusOrAgsSubjectClassification"})
@XmlRootElement(name = "dc:subject")
public class DcSubject implements Annotatable{

	@XmlMixed
	@XmlElementRefs ({
	  @XmlElementRef(name = "ags:subjectThesaurus", type = AgsSubjectThesaurus.class),
	  @XmlElementRef(name = "ags:subjectClassification", type = AgsSubjectClassification.class)
	})
//    @XmlAttribute(name = "xml:lang")
//    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
//    protected String xmlLang;
//    @XmlValue
//    protected String value;
    
    protected List<Object> agsSubjectThesaurusOrAgsSubjectClassification;

//    /**
//     * Gets the value of the xmlLang property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getXmlLang() {
//        return xmlLang;
//    }
//
//    /**
//     * Sets the value of the xmlLang property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setXmlLang(String value) {
//        this.xmlLang = value;
//    }
//
//    /**
//     * Gets the value of the value property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getvalue() {
//        return value;
//    }
//
//    /**
//     * Sets the value of the value property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setvalue(String value) {
//        this.value = value;
//    }

    public List<Object> getAgsSubjectThesaurusOrAgsSubjectClassification() {
        if (agsSubjectThesaurusOrAgsSubjectClassification == null) {
        	agsSubjectThesaurusOrAgsSubjectClassification = new ArrayList<Object>();
        }
        return this.agsSubjectThesaurusOrAgsSubjectClassification;
    }

	@Override
	public String getvalue() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setvalue(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getOrcid() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setOrcid(String orcid) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getViaf() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setViaf(String viaf) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getOnld() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setOnld(String onld) {
		// TODO Auto-generated method stub
		
	}
}
