//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 02:35:22 PM EET 
//


package com.agroknow.schema.agrisap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.agroknow.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.agroknow.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DcFormat }
     * 
     */
    public DcFormat createDcFormat() {
        return new DcFormat();
    }

    /**
     * Create an instance of {@link DctermsExtent }
     * 
     */
    public DctermsExtent createDctermsExtent() {
        return new DctermsExtent();
    }

    /**
     * Create an instance of {@link DctermsMedium }
     * 
     */
    public DctermsMedium createDctermsMedium() {
        return new DctermsMedium();
    }

    /**
     * Create an instance of {@link DctermsRequires }
     * 
     */
    public DctermsRequires createDctermsRequires() {
        return new DctermsRequires();
    }

    /**
     * Create an instance of {@link DcType }
     * 
     */
    public DcType createDcType() {
        return new DcType();
    }

    /**
     * Create an instance of {@link AgsAvailabilityLocation }
     * 
     */
    public AgsAvailabilityLocation createAgsAvailabilityLocation() {
        return new AgsAvailabilityLocation();
    }

    /**
     * Create an instance of {@link AgsPublisherName }
     * 
     */
    public AgsPublisherName createAgsPublisherName() {
        return new AgsPublisherName();
    }

    /**
     * Create an instance of {@link AgsAvailabilityNumber }
     * 
     */
    public AgsAvailabilityNumber createAgsAvailabilityNumber() {
        return new AgsAvailabilityNumber();
    }

    /**
     * Create an instance of {@link DctermsSpatial }
     * 
     */
    public DctermsSpatial createDctermsSpatial() {
        return new DctermsSpatial();
    }

    /**
     * Create an instance of {@link DcTitle }
     * 
     */
    public DcTitle createDcTitle() {
        return new DcTitle();
    }

    /**
     * Create an instance of {@link AgsCitationTitle }
     * 
     */
    public AgsCitationTitle createAgsCitationTitle() {
        return new AgsCitationTitle();
    }

    /**
     * Create an instance of {@link AgsRightsStatement }
     * 
     */
    public AgsRightsStatement createAgsRightsStatement() {
        return new AgsRightsStatement();
    }

    /**
     * Create an instance of {@link DctermsAlternative }
     * 
     */
    public DctermsAlternative createDctermsAlternative() {
        return new DctermsAlternative();
    }

    /**
     * Create an instance of {@link DctermsIsReplacedBy }
     * 
     */
    public DctermsIsReplacedBy createDctermsIsReplacedBy() {
        return new DctermsIsReplacedBy();
    }

    /**
     * Create an instance of {@link DctermsIsPartOf }
     * 
     */
    public DctermsIsPartOf createDctermsIsPartOf() {
        return new DctermsIsPartOf();
    }

    /**
     * Create an instance of {@link AgsResource }
     * 
     */
    public AgsResource createAgsResource() {
        return new AgsResource();
    }

    /**
     * Create an instance of {@link DcCreator }
     * 
     */
    public DcCreator createDcCreator() {
        return new DcCreator();
    }

    /**
     * Create an instance of {@link DcPublisher }
     * 
     */
    public DcPublisher createDcPublisher() {
        return new DcPublisher();
    }

    /**
     * Create an instance of {@link DcDate }
     * 
     */
    public DcDate createDcDate() {
        return new DcDate();
    }

    /**
     * Create an instance of {@link DcSubject }
     * 
     */
    public DcSubject createDcSubject() {
        return new DcSubject();
    }

    /**
     * Create an instance of {@link DcDescription }
     * 
     */
    public DcDescription createDcDescription() {
        return new DcDescription();
    }

    /**
     * Create an instance of {@link DcIdentifier }
     * 
     */
    public DcIdentifier createDcIdentifier() {
        return new DcIdentifier();
    }

    /**
     * Create an instance of {@link DcLanguage }
     * 
     */
    public DcLanguage createDcLanguage() {
        return new DcLanguage();
    }

    /**
     * Create an instance of {@link DcRelation }
     * 
     */
    public DcRelation createDcRelation() {
        return new DcRelation();
    }

    /**
     * Create an instance of {@link AglsAvailability }
     * 
     */
    public AglsAvailability createAglsAvailability() {
        return new AglsAvailability();
    }

    /**
     * Create an instance of {@link DcSource }
     * 
     */
    public DcSource createDcSource() {
        return new DcSource();
    }

    /**
     * Create an instance of {@link DcCoverage }
     * 
     */
    public DcCoverage createDcCoverage() {
        return new DcCoverage();
    }

    /**
     * Create an instance of {@link DcRights }
     * 
     */
    public DcRights createDcRights() {
        return new DcRights();
    }

    /**
     * Create an instance of {@link AgsCitation }
     * 
     */
    public AgsCitation createAgsCitation() {
        return new AgsCitation();
    }

    /**
     * Create an instance of {@link DctermsHasPart }
     * 
     */
    public DctermsHasPart createDctermsHasPart() {
        return new DctermsHasPart();
    }

    /**
     * Create an instance of {@link DctermsIsVersionOf }
     * 
     */
    public DctermsIsVersionOf createDctermsIsVersionOf() {
        return new DctermsIsVersionOf();
    }

    /**
     * Create an instance of {@link DctermsHasVersion }
     * 
     */
    public DctermsHasVersion createDctermsHasVersion() {
        return new DctermsHasVersion();
    }

    /**
     * Create an instance of {@link DctermsIsFormatOf }
     * 
     */
    public DctermsIsFormatOf createDctermsIsFormatOf() {
        return new DctermsIsFormatOf();
    }

    /**
     * Create an instance of {@link DctermsHasFormat }
     * 
     */
    public DctermsHasFormat createDctermsHasFormat() {
        return new DctermsHasFormat();
    }

    /**
     * Create an instance of {@link DctermsReferences }
     * 
     */
    public DctermsReferences createDctermsReferences() {
        return new DctermsReferences();
    }

    /**
     * Create an instance of {@link DctermsIsReferencedBy }
     * 
     */
    public DctermsIsReferencedBy createDctermsIsReferencedBy() {
        return new DctermsIsReferencedBy();
    }

    /**
     * Create an instance of {@link DctermsIsRequiredBy }
     * 
     */
    public DctermsIsRequiredBy createDctermsIsRequiredBy() {
        return new DctermsIsRequiredBy();
    }

    /**
     * Create an instance of {@link DctermsReplaces }
     * 
     */
    public DctermsReplaces createDctermsReplaces() {
        return new DctermsReplaces();
    }

    /**
     * Create an instance of {@link AgsRelationHasTranslation }
     * 
     */
    public AgsRelationHasTranslation createAgsRelationHasTranslation() {
        return new AgsRelationHasTranslation();
    }

    /**
     * Create an instance of {@link AgsRelationIsTranslationOf }
     * 
     */
    public AgsRelationIsTranslationOf createAgsRelationIsTranslationOf() {
        return new AgsRelationIsTranslationOf();
    }

    /**
     * Create an instance of {@link AgsTitleSupplement }
     * 
     */
    public AgsTitleSupplement createAgsTitleSupplement() {
        return new AgsTitleSupplement();
    }

    /**
     * Create an instance of {@link AgsCitationChronology }
     * 
     */
    public AgsCitationChronology createAgsCitationChronology() {
        return new AgsCitationChronology();
    }

    /**
     * Create an instance of {@link AgsResources }
     * 
     */
    public AgsResources createAgsResources() {
        return new AgsResources();
    }

    /**
     * Create an instance of {@link AgsCitationNumber }
     * 
     */
    public AgsCitationNumber createAgsCitationNumber() {
        return new AgsCitationNumber();
    }

    /**
     * Create an instance of {@link DctermsAbstract }
     * 
     */
    public DctermsAbstract createDctermsAbstract() {
        return new DctermsAbstract();
    }

    /**
     * Create an instance of {@link AgsSubjectClassification }
     * 
     */
    public AgsSubjectClassification createAgsSubjectClassification() {
        return new AgsSubjectClassification();
    }

    /**
     * Create an instance of {@link AgsDescriptionNotes }
     * 
     */
    public AgsDescriptionNotes createAgsDescriptionNotes() {
        return new AgsDescriptionNotes();
    }

    /**
     * Create an instance of {@link AgsDescriptionEdition }
     * 
     */
    public AgsDescriptionEdition createAgsDescriptionEdition() {
        return new AgsDescriptionEdition();
    }

    /**
     * Create an instance of {@link AgsSubjectThesaurus }
     * 
     */
    public AgsSubjectThesaurus createAgsSubjectThesaurus() {
        return new AgsSubjectThesaurus();
    }

    /**
     * Create an instance of {@link AgsCitationIdentifier }
     * 
     */
    public AgsCitationIdentifier createAgsCitationIdentifier() {
        return new AgsCitationIdentifier();
    }

    /**
     * Create an instance of {@link DctermsTemporal }
     * 
     */
    public DctermsTemporal createDctermsTemporal() {
        return new DctermsTemporal();
    }

    /**
     * Create an instance of {@link DctermsDateIssued }
     * 
     */
    public DctermsDateIssued createDctermsDateIssued() {
        return new DctermsDateIssued();
    }

    /**
     * Create an instance of {@link AgsRightsTermsOfUse }
     * 
     */
    public AgsRightsTermsOfUse createAgsRightsTermsOfUse() {
        return new AgsRightsTermsOfUse();
    }

    /**
     * Create an instance of {@link AgsCreatorCorporate }
     * 
     */
    public AgsCreatorCorporate createAgsCreatorCorporate() {
        return new AgsCreatorCorporate();
    }

    /**
     * Create an instance of {@link AgsPublisherPlace }
     * 
     */
    public AgsPublisherPlace createAgsPublisherPlace() {
        return new AgsPublisherPlace();
    }

    /**
     * Create an instance of {@link AgsCreatorConference }
     * 
     */
    public AgsCreatorConference createAgsCreatorConference() {
        return new AgsCreatorConference();
    }

    /**
     * Create an instance of {@link AgsCreatorPersonal }
     * 
     */
    public AgsCreatorPersonal createAgsCreatorPersonal() {
        return new AgsCreatorPersonal();
    }

}
